services:
  speedtest-monitor:
    restart: unless-stopped
    image: tianon/speedtest
    container_name: speedtest-monitor
    working_dir: /root
    network_mode: host
    environment:
      - TZ=Asia/Taipei
      - EXPORT_JSONL=true
      - EXPORT_SQLITE=true
    volumes:
      - $PWD:/root
    command: sh -c "
      apk add tzdata jq sqlite --no-cache &&
      chmod +x /root/record.sh &&
      crontab /root/tasks.cron &&
      crond -f -L /dev/stdout"
